notifications:
  email: false
language: csharp
install:
  - mono ./.paket/paket.exe restore
  - nuget install NUnit.ConsoleRunner -Version 3.6.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Kl.Net45.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./Kl.Tests.Net45/bin/Release/Kl.Tests.dll
  - mono ./Kl.Get.Net45/bin/Release/Kl.Get.exe
  - mono ./Kl.Make.Net45/bin/Release/Kl.Make.exe
  - xbuild /p:Configuration=Release Shen.Net45.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./Shen.Tests.Net45/bin/Release/Shen.Tests.dll
  - mono ./Shen.TestSuite.Net45/bin/Release/Shen.TestSuite.exe
