before_build:
  - .\.paket\paket.exe restore
  - nuget install NUnit.ConsoleRunner -Version 3.6.0 -OutputDirectory testrunner
build_script:
  - msbuild /p:Configuration=Release Kl.Net45.sln
  - .\testrunner\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe .\Kl.Tests.Net45\bin\Release\Kl.Tests.dll
  - .\Kl.Get.Net45\bin\Release\Kl.Get.exe
  - .\Kl.Make.Net45\bin\Release\Kl.Make.exe
  - msbuild /p:Configuration=Release Shen.Net45.sln
  - .\testrunner\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe .\Shen.Tests.Net45\bin\Release\Shen.Tests.dll
  - .\Shen.TestSuite.Net45\bin\Release\Shen.TestSuite.exe
